const data = {
  data:[
    {
      id:0,
      price:89,
      quantity:0,
      name:"Nike",
      img:"nike1.jpg"
    },
    {
      id:1,
      price:67,
      quantity:0,
      name:"Nike",
      img:"nike2.jpg"
    },
    {
      id:2,
      price:214,
      quantity:0,
      name:"Nike",
      img:"nike3.jpg"
    },
    {
      id:3,
      price:235,
      quantity:0,
      name:"Nike",
      img:"nike4.jpg"
    },
    {
      id:4,
      price:300,
      quantity:0,
      name:"Nike",
      img:"nike5.jpg"
    },
    {
      id:5,
      price:74,
      quantity:0,
      name:"Nike",
      img:"nike6.jpg"
    },
    {
      id:6,
      price:245,
      quantity:0,
      name:"Nike",
      img:"nike7.jpg"
    },
    {
      id:7,
      price:125,
      quantity:0,
      name:"Nike",
      img:"nike8.jpg"
    },
    {
      id:8,
      price:125,
      quantity:0,
      name:"Nike",
      img:"nike9.jpg"
    },
    {
      id:9,
      price:555,
      quantity:0,
      name:"Nike",
      img:"nike10.jpg"
    },
    {
      id:10,
      price:233,
      quantity:0,
      name:"Nike",
      img:"nike11.jpg"
    },
    {
      id:11,
      price:123,
      quantity:0,
      name:"Nike",
      img:"nike12.png"
    },
    {
      id:12,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike13.png"
    },
    {
      id:13,
      price:455,
      quantity:0,
      name:"Nike",
      img:"nike14.png"
    },
    {
      id:14,
      price:75,
      quantity:0,
      name:"Nike",
      img:"nike15.png"
    },
    {
      id:15,
      price:55,
      quantity:0,
      name:"Nike",
      img:"nike16.png"
    },
    {
      id:16,
      price:356,
      quantity:0,
      name:"Nike",
      img:"nike17.png"
    },
    {
      id:17,
      price:155,
      quantity:0,
      name:"Nike",
      img:"nike18.png"
    },
    {
      id:18,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike19.png"
    },
    {
      id:19,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike20.png"
    },
    {
      id:20,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike21.png"
    },
    {
      id:21,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike22.png"
    },
    {
      id:22,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike23.png"
    },
    {
      id:23,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike24.png"
    },
    {
      id:24,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike25.png"
    },
    {
      id:25,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike26.png"
    },
    {
      id:26,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike27.png"
    },
    {
      id:27,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike28.png"
    },
    {
      id:28,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike29.png"
    },
    {
      id:29,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike30.png"
    },
    {
      id:30,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike31.png"
    },
    {
      id:31,
      price:255,
      quantity:0,
      name:"Nike",
      img:"nike32.png"
    }
  ]
}

export default data